### ISSUE TITLE
Ошибка после обновления fake_useragent

### ISSUE THREAD

**Issue by PrometheusAla** [Alexell/XEmpireBot#102]
Traceback (most recent call last):
  File "C:\Users\Professional\Downloads\XEmpireBot-main\XEmpireBot-Battle\main.py", line 2, in <module>
    from bot.core import launcher
  File "C:\Users\Professional\Downloads\XEmpireBot-main\XEmpireBot-Battle\bot\core\launcher.py", line 7, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

Установил модуль через pip install fake-useragent - но ошибка осталась (

**Comment by PrometheusAla** [comment]
Разобрался. Переустановил скрипт.

**Comment by Alexell** [comment]
На будущее: если какой-то python софт после обновления выдает ошибку отсутствия какого-либо модуля, значит проект стал использовать новый сторонний модуль и вам нужно всего лишь перейди в папку проекта и повторно выполнить команду установки зависимостей, она доустановит новый модуль. Например в этом боте:
```shell
cd XEmpireBot
source venv/bin/activate
pip3 install -r requirements.txt
deactivate
```
