### ISSUE TITLE
Please Fix

### ISSUE THREAD

**Issue by NamasteIndia** [Alexell/XEmpireBot#110]
2024-09-07 05:52:07 | ERROR    | 164 | SUKUMAR | Profile data http error: Bad Gateway
2024-09-07 05:52:10 | ERROR    | 1023 | SUKUMAR | Unknown error: 'hero'

**Comment by Alexell** [comment]
Bad gateway - an error on the game server side, the bot has nothing to do with it. Just restart the bot if it can't handle the error itself.

**Comment by NamasteIndia** [comment]
I have tried restarting but the error still persists. Along with this new error 
`"2024-09-07 05:51:12 | ERROR    | 641 | SUKUMAR | Improve skill http error: Bad Gateway"`

**Comment by Alexell** [comment]
I checked on different accounts, there is no such problem. Do you use a proxy?

**Comment by lucasnguyen3979** [comment]
I have this error, all my accounts have username:

![image](https://github.com/user-attachments/assets/91fb8c17-18eb-46c8-98b3-8f24533cd846)

**Comment by NamasteIndia** [comment]
Same just like mine, it will keep trying for a while then it will get
connected.

**Comment by Alexell** [comment]
@lucasnguyen3979 fixed in 4089cfb68c64a120904fc1cebff0da948d52369e

**Comment by NamasteIndia** [comment]
well i am not using any proxy :)
