### ISSUE TITLE
Cannot Create Session

### ISSUE THREAD

**Issue by khosrowkhazraei** [Alexell/XEmpireBot#20]
After entering the Phone Number, I do not recive the verificaiton code in the telegram, what is wrong?

**Comment by cr4zyfish** [comment]
Do you enter it in correct format? +989203004050 ?

**Comment by khosrowkhazraei** [comment]
Yes

I tried too much
Even with bot token
I don't know what the problem is

The old seasons I have they Work, but now I wanna create new sessions for
another PC, it fais with not receiving OTP in the telegram app.

I tried logging the telegram in web to see if I receive code, it was
successful


Could you please confirm if you can create new sessions?

**Comment by Duwaz** [comment]
> Could you please confirm if you can create new sessions?

You wrote about an error from a standard Python library - pyrogram. It's not about bot logic... *There is nobody known your auth-data. Of course

I guess, your problem seems like a problem with Telegram...

As a backup plan, you can copy a file from another PC. *see folder `sessions` (copy to the same folder)

**Comment by khosrowkhazraei** [comment]
Yes as I said it is about the program package (session ) not the bot

Thank you for your responses

I will try to figure it out

**Comment by QuiglyGames** [comment]
I get this error when I try to create a new session, maybe you have the same thing, I hope they will tell me what to do with it.

```
Select an action:
    1. Create session
    2. Run bot

> 1

Enter the session name (press Enter to exit): 1
Traceback (most recent call last):
  File "C:\Users\Watching\MuskEmpireBot\main.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\Watching\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Watching\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Watching\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Watching\MuskEmpireBot\main.py", line 6, in main
    await launcher.start()
  File "C:\Users\Watching\MuskEmpireBot\bot\core\launcher.py", line 103, in start
    await register_sessions()
  File "C:\Users\Watching\MuskEmpireBot\bot\core\launcher.py", line 27, in register_sessions
    if not os.path.exists(path='sessions'): os.mkdir(path='sessions')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
```

**Comment by Alexell** [comment]
Use Python 3.10. I do not guarantee or support the bot's operation on other versions of Python.

**Comment by alina1488** [comment]
![image](https://github.com/user-attachments/assets/1eda7e93-c8da-4458-8686-9b8affe862dd)

How to fix it

**Comment by madkite2** [comment]
> How to fix it

The developer is aware of the problem. Will try to solve it soon

**Comment by Duwaz** [comment]
> How to fix it

I saw the same situation in a hamster bot... Do you have problem when your money per hour more then zero?

**Comment by Alexell** [comment]
@alina1488 your problem is in your proxy.

**Comment by vainzew** [comment]
![image](https://github.com/user-attachments/assets/1c0a9158-8afa-43ed-96de-8b94e3f2f882)

Hi, i've got this error and don't know how to resolve it. can you help me with this?

**Comment by Alexell** [comment]
@vainzew Using Python **3.10** is mandatory!

**Comment by Ja1zen** [comment]
Hey, after selecting action (1. Create Session) nothing happens. 
![image](https://github.com/user-attachments/assets/64e6c935-5219-4157-b51e-57b86d189334)
