### ISSUE TITLE
Смена json файла для прокачки

### ISSUE THREAD

**Issue by furzich2015** [Alexell/XEmpireBot#21]
Посколько я с Украини (думаю есть люди которые так же с Украины) они не смогут получать данние з json посколько домен не доступен.
![image](https://github.com/user-attachments/assets/075fcade-8709-4be7-a380-93ad32cef431)
Если есть возможность сменить ето на другой домен (не .ru) или зделать зеркало, было бы отлично.
Спасибо.

**Comment by Alexell** [comment]
У вас там только блокировка зоны .ru или российские ip адреса тоже блокируются?

**Comment by furzich2015** [comment]
> У вас там только блокировка зоны .ru или российские ip адреса тоже блокируются?

Домена .ru и IP сетки тоже

**Comment by Alexell** [comment]
Все мои VPS на российском хостинге. Хм, а если домен не .ru, хостинг ру, но сайт за CloudFlare, то будет доступ? Проверьте, доступен ли вот этот мой сайт, он как раз по этой схеме: https://uni-tools.net/

**Comment by furzich2015** [comment]
> Все мои VPS на российском хостинге. Хм, а если домен не .ru, хостинг ру, но сайт за CloudFlare, то будет доступ? Проверьте, доступен ли вот этот мой сайт, он как раз по этой схеме: https://uni-tools.net/

Да, он доступен
![image](https://github.com/user-attachments/assets/f3ec22bc-40ce-457a-81a1-6ce1b7b9ee45)

**Comment by Alexell** [comment]
Хорошо, тогда завтра возьму еще один домен не в зоне .ru (все равно планировал это сделать для будущего лендинга) и перенесу json туда.

**Comment by furzich2015** [comment]
> Хорошо, тогда завтра возьму еще один домен не в зоне .ru (все равно планировал это сделать для будущего лендинга) и перенесу json туда.

Супер, благодарю! Дай знать как будет доступно.

**Comment by Alexell** [comment]
@furzich2015 выполнено.
