### ISSUE TITLE
Login error: Cannot connect to host api.muskempire.io:443 ssl

### ISSUE THREAD

**Issue by zv09** [Alexell/XEmpireBot#22]
Выдает ошибку : 

```
> (venv) MBP:MuskEmpireBot =$ > python3 main.py -a 2
> 2024-08-03 23:01:27 | INFO     | 90 | Detected 1 sessions | 0 proxies
> 2024-08-03 23:01:27 | INFO     | 83 | = | Trying to login...
> 2024-08-03 23:01:29 | ERROR    | 93 | = | Login error: Cannot connect to host api.muskempire.io:443 ssl:True [SSLCertVerificationError: (5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
```

**Comment by zv09** [comment]
поменял api на `https://api.xempire.io`
```
	'Origin': 'https://game.xempire.io/',
	'Referer': 'https://game.xempire.io/',
```
Тоже самое. Ошибка SSL. 
`Login error: Cannot connect to host api.xempire.io:443 ssl:True [SSLCertVerificationError: (5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]`

**Comment by zv09** [comment]
It's updated.. 
I fetch it again, rebuild with env and the same error...
What is the problem can be? 
Can suggest, pls? 


<img width="1356" alt="Screen Shot 2024-08-06 at 23 35 39" src="https://github.com/user-attachments/assets/d4958199-66c1-4586-b820-6c7a74af9e9d">

**Comment by Alexell** [comment]
У меня, как и у других, такой проблемы нет. Бот прекрасно работает. Оставлю проблему открытой, может быть кто-то другой сможет помочь.
P.S. Ты уж определись, по русски ты пишешь или по английски.
__
I, like others, do not have such a problem. The bot works fine. I will leave the problem open, maybe someone else can help.
P.S. You should decide whether you write in Russian or English.

**Comment by zv09** [comment]
ok, тут разные проекты и иногда мозг не переключается..
попробую pyrogram покрутить... я всегда телетон юзал, пирогу не знаю...
отпишу если вылечу... спасибо

**Comment by Alexell** [comment]
Еще такой вариант: если у тебя Python не 3.10, поставь 3.10 и скорее всего всё вылечится.

**Comment by zv09** [comment]
3.12, 
понял... 
ну я его проблемно кстати поставил. 
там 310 и 311 были с макпортов + нативный 2 в macOS
когда 312 ставил, он каким то образом порушил окружение и снес пипы, ссылки руками восстанавливал 
видимо там проблема
спасибо

**Comment by zv09** [comment]
python3.12 не мог найти  requests в env
и он туда не ставился, pip возвращал ошибку сертификата SSL и не мог фетчить модуль с pip repo... 
решилось так: 
все команды в venv 
```
(venv) MBP:XEmpireBot x$ > pip install pip-system-certs
Requirement already satisfied: pip-system-certs in ./venv/lib/python3.12/site-packages (4.0)
Requirement already satisfied: wrapt>=1.10.4 in ./venv/lib/python3.12/site-packages (from pip-system-certs) (1.16.0)
```

не дает ставить requests
```
(venv) MBP:XEmpireBot x$ > pip install requests

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/requests/

Could not fetch URL https://pypi.org/simple/requests/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))) - skipping

ERROR: Could not find a version that satisfies the requirement requests (from versions: none)
ERROR: No matching distribution found for requests
```
переустановка руками requests через pypi в venv
```
(venv) MBP:XEmpireBot x$ > pip install --trusted-host pypi.org requests

Installing collected packages: urllib3, charset-normalizer, certifi, requests
Successfully installed certifi-2024.7.4 charset-normalizer-3.3.2 requests-2.32.3 urllib3-2.2.2
```

проверка: 
```
(venv) MBP:XEmpireBot x$ > python -c "import requests; print (requests.certs.where())"
/Users/x/Projects/XEmpireBot/venv/lib/python3.12/site-packages/certifi/cacert.pem
```

проверка SSL в venv и там проблема: 
```
(venv) MBP:XEmpireBot x$ > $SSL_CERT_DIR 
-bash: /etc/ssl/certs/: is a directory
```

перенаправляем: 
`(venv) MBP:XEmpireBot  x$ > export SSL_CERT_FILE=/Users/x/Projects/XEmpireBot/venv/lib/python3.12/site-packages/certifi/cacert.pem`

Permission denied далее не влияет: на практике : 
```
(venv) MBP:XEmpireBot x$ > $SSL_CERT_FILE
-bash: /Users/x/Projects/XEmpireBot/venv/lib/python3.12/site-packages/certifi/cacert.pem: Permission denied
```
проверка контакта
```
(venv) MBP:XEmpireBot x$ > python -c 'import requests; print (requests.get("https://example.com"))'
<Response [200]>
```
есть контакт: 
```
(venv) MBP:XEmpireBot x$ > python3 main.py
2024-08-07 23:00:47 | INFO     | 90 | Detected 1 sessions | 0 proxies

2024-08-07 23:00:50 | INFO     | 84 | X | Trying to login...
2024-08-07 23:00:51 | SUCCESS  | 552 | X | Login successful
2024-08-07 23:00:53 | SUCCESS  | 564 | X | Offline bonus claimed: +24678540
2024-08-07 23:00:55 | INFO     | 573 | X | Level: 12 | Balance: 24761563 | Money per hour: 15267700
```

Всем спасибо,
