### ISSUE TITLE
Update sleep time after each energy run out

### ISSUE THREAD

**Issue by lucasnguyen3979** [Alexell/XEmpireBot#24]
Update sleep time after each energy run out should be based on energy per second ratio...

![image](https://github.com/user-attachments/assets/48aab1e2-b768-464d-aa0c-77510ab71912)

**Comment by Alexell** [comment]
This timer has nothing to do with energy, it's just a 1 hour timer to get offline bonus and do all the actions in a circle. Taps are not needed at all in this game, because the income per hour is many times more than you can get with taps.

**Comment by lucasnguyen3979** [comment]
@Alexell hmm I don't know but my energy is always full during that sleep time... Btw the improve skill feature is not working right?

**Comment by Alexell** [comment]
Skill improvement works. Maybe not for everyone. But on the level 14 and 16 accounts I checked, everything works fine. But it will still need some improvements, one way or another.
