### ISSUE TITLE
Unknown error: 'servers' and Unknown error: 'foosball'

### ISSUE THREAD

**Issue by molotov95** [Alexell/XEmpireBot#28]
В логах появлялось 2 ошибки которые перезапускали сессии циклически у одной сессии это Unknown error: 'servers' у другой Unknown error: 'foosball'. Проявлялась она после игр PVP и расчета прибыли, Возможно это связанно с тем что установил большое количество игр 50 подряд?)))

**Comment by Alexell** [comment]
Прикладывайте полные логи или скриншоты.

**Comment by Alexell** [comment]
@molotov95 
**Если проблема еще актуальна:**
- обновите бот до свежей версии (команда: `git pull`)
- укажите **DEBUG_MODE=True** в вашем `.env`
- запустите бота с **ОБЯЗАТЕЛЬНЫМ** перенаправлением stdout в файл: `venv/bin/python3 main.py --action 2 >> app.log 2>&1`
- проверяйте содержимое `app.log` и ждите появления ошибок (ERROR), затем остановите бота
- приложите сюда ваш `app.log` для анализа и устранения проблемы

**Comment by Alexell** [comment]
Отсутствие ответа длительное время. Закрываю.
