### ISSUE TITLE
Значение баланса

### ISSUE THREAD

**Issue by almir20122** [Alexell/XEmpireBot#30]
Нельзя ли перевести значение баланса примерно на вот такую цифру? 100,000,000 или 100млн, Думаю  так смотрибельнее будет) Спасибо заранее за ответ)

**Comment by sanyapg** [comment]
https://github.com/Alexell/XEmpireBot/pull/29

**Comment by Alexell** [comment]
ce7cccd5ae8d920637f57ac9d920e84d1e505612
