### ISSUE TITLE
Unknown error: list index out of range

### ISSUE THREAD

**Issue by madest18** [Alexell/XEmpireBot#32]
бот со следующими настройками
TAPS_ENABLED=False
TAPS_PER_SECOND=
PVP_ENABLED=False
PVP_LEAGUE=
PVP_UPGRADE_LEAGUE=True
PVP_STRATEGY=aggressive
PVP_COUNT=5
SKILLS_COUNT=10
PROTECTED_BALANCE=0

SLEEP_BETWEEN_START=
ERRORS_BEFORE_STOP=
USE_PROXY_FROM_FILE=True
как я понимаю бот не видит, что прокачивать нечего и не засыпает на 1 час
заходит в игру с телефона, видел что денег нет.
скрин ниже.

![image](https://github.com/user-attachments/assets/bad4d59b-bdf4-4dd8-ac9f-3e2970aaaec9)

**Comment by Alexell** [comment]
@madest18 
**Если проблема еще актуальна:**
- обновите бот до свежей версии (команда: `git pull`)
- укажите **DEBUG_MODE=True** в вашем `.env`
- запустите бота с **ОБЯЗАТЕЛЬНЫМ** перенаправлением stdout в файл: `venv/bin/python3 main.py --action 2 >> app.log 2>&1`
- проверяйте содержимое `app.log` и ждите появления ошибок (ERROR), затем остановите бота
- приложите сюда ваш `app.log` для анализа и устранения проблемы
