### ISSUE TITLE
start session

### ISSUE THREAD

**Issue by SmILeTheMobster** [Alexell/XEmpireBot#33]
Hi all, I realize that I am weak enough for all this, but please tell me what is needed to start a session in the bot? Where to get the data to fill proxies.txt or how to make the bot see my session?

**Comment by Alexell** [comment]
If you use 1 account, then you do not need proxies. If you are going to run a bot on several accounts at once on one server (or PC), then you must buy proxies and register them in `proxy.txt`, and also specify **USE_PROXY_FROM_FILE=True** in `.env`

**And launching the bot is simple:**
- Launch the bot.
- Select action 1 - Create session, log in to the Telegram account. You can repeat this step and authorize a second Telegram account if needed.
- Launch the bot and select action number 2 - Run bot.

**It is highly not recommended to run multiple accounts without a proxy.**

**Comment by SmILeTheMobster** [comment]
> If you use 1 account, then you do not need proxies. If you are going to run a bot on several accounts at once on one server (or PC), then you must buy proxies and register them in `proxy.txt`, and also specify **USE_PROXY_FROM_FILE=True** in `.env`
> 
> **And launching the bot is simple:**
> 
> * Launch the bot.
> * Select action 1 - Create session, log in to the Telegram account. You can repeat this step and authorize a second Telegram account if needed.
> * Launch the bot and select action number 2 - Run bot.
> 
> **It is highly not recommended to run multiple accounts without a proxy.**

![image](https://github.com/user-attachments/assets/fd9b0ffb-c0a8-465a-8bc9-87d9560cabe3)
I feel awkward, but how to authorize, when I write the session name I get an error.

**Comment by Alexell** [comment]
@SmILeTheMobster You need to use **Python 3.10**. Only this version!

**Comment by SmILeTheMobster** [comment]
> @SmILeTheMobster You need to use **Python 3.10**. Only this version! There won't be any problems with this version.
> 
> P.S. Зачем ты пишешь по английски, у тебя винда на русском, на скрине видно. Ребят, не усложняйте мне жизнь. Русскоговорящие, пишите на русском, остальные пусть на английском пишут.

![image](https://github.com/user-attachments/assets/19133b34-7751-48c4-a53b-8070794e781f)
сори) спасибо кста, все работает
