### ISSUE TITLE
По ветке прокачки скилов - ИИ. 

### ISSUE THREAD

**Issue by iLimus** [Alexell/XEmpireBot#35]
Не замечал ни разу, чтоб бот прокачивал что то из новой ветки - ИИ. Качает что то только из обычных трех веток.
Он не видит скилы оттуда?

**Comment by elektrohouse0** [comment]
> Не замечал ни разу, чтоб бот прокачивал что то из новой ветки - ИИ. Качает что то только из обычных трех веток. Он не видит скилы оттуда?

когда ветка ИИ открывается?

**Comment by Alexell** [comment]
@iLimus я еще не достиг 20 уровня, так что не могу ничего сказать по этому поводу.

**Comment by iLimus** [comment]
Хорошо, спасибо, подожду...
Тогда еще просьба - можно ли сделать отдельно прокачку "мусорных" скилов Команды до заданного значения?
В новой ветке ИИ некоторые пункты прокачки требуют прокачки, к примеру, менеджера по продажам до 150 уровня, или Программистов до 100го... И это только для открытия скилла. Потом могут и больше попросить. Пальцем тыкать долго и нудно...

**Comment by Alexell** [comment]
Полагаю, что рано или поздно, бот все эти необходимые навыки так и так прокачает до нужного уровня, после чего, скорее всего сам автоматически сможет прокачивать навыки из раздела "ИИ", если конечно сочтет их прибыльными. Кроме того, у меня даже представления нет, как реализовать такое.

**Comment by Alexell** [comment]
Я был прав. Этой ночью, бот достиг 20 уровня, я сейчас зашел в игру, пока бот спит час и увидел, что навыки из ИИ уже прокачались до 6-7 уровня, по крайней мере те, которые доступны для прокачки.
