### ISSUE TITLE
Money format

### ISSUE THREAD

**Issue by seligor** [Alexell/XEmpireBot#38]
2024-08-07 17:33:05 | INFO | 563 | MuskEmpire | Level: 17 | Balance: 93 877 015 | Money per hour: 138 733 525

bot.py
564 `{'{0:,}'.format(self.balance).replace(',', ' ')}`
565 `{'{0:,}'.format(self.mph).replace(',', ' ')}`
684 `{'{0:,}'.format(self.balance).replace(',', ' ')}`
685 `{'{0:,}'.format(self.mph).replace(',', ' ')}`

**Comment by Alexell** [comment]
Money formatting will be done in the next updates. Please wait.

**Comment by Alexell** [comment]
ce7cccd5ae8d920637f57ac9d920e84d1e505612
