### ISSUE TITLE
Humanize intervals

### ISSUE THREAD

**Issue by zv09** [Alexell/XEmpireBot#40]
В список вношу разные значения. 
Все по часу в sleep выходит. 
SLEEP_BETWEEN_START: list[int] = [60, 600]
На 3 часа хочу поставить. 

но эта задержка всегда в час 
`2024-08-08 06:10:54 | INFO     | 715 | x | Sleep 1 hour`

**Comment by Alexell** [comment]
SLEEP_BETWEEN_START не имеет отношения к строке лога, которую вы написали. SLEEP_BETWEEN_START нужен только тогда, когда у вас несколько сессий на боте и при старте бота, сессии будут запускаться по очереди с этой задержкой, чтобы не было палевно сразу все сессии запускать.

Сон между рабочими циклами всегда час, это не настраивается. Но могу сделать, если соберется хотя бы 5 желающих.

**Comment by zv09** [comment]
создадите может группу в телеге на обсуждение ботоводства. ссылку в ридми
я тут одну нашел по HK, там они ферму написали с кучей ботов-модулей.

**Comment by zv09** [comment]
ГОЛОСУЙТЕ и ПЛЮСУЙТЕ люди за настраиваемый параметр задержки рабочего цикла!  +4 юзера

PLEASE VOTE to add a manageable parameter for pauses between cycles in settings.. We need +4 users more...

**Comment by WanterDehka** [comment]
Обновил папбку bots, и куда то тапы пропали в боте, перестал тапать короче, а сегодня походу подвезли обнову скилы по тапам, и бонус с тапанье

**Comment by zv09** [comment]
> Обновил папбку bots, и куда то тапы пропали в боте, перестал тапать короче, а сегодня походу подвезли обнову скилы по тапам, и бонус с тапанье, новая вклада добыча

все нормально тапает
`2024-08-08 16:56:20 | SUCCESS  | 308 | x | Earned money: +414 | Energy left: 5793`

**Comment by WanterDehka** [comment]
> > Обновил папбку ботов, и куда то тапы пропали в боте, начал тапать кресты, а сегодня походу подвезли обнову скилы по тапам, и бонус с тапанье, новый вклад добыча
> 
> все нормально тапает `2024-08-08 16:56:20 | SUCCESS | 308 | x | Earned money: +414 | Energy left: 5793`

все нормально, второй запуск начал тапать

**Comment by elektrohouse0** [comment]
Полностью согласен по поводу гибкой настройки бота, + ко всем выше описанным позициям. Было бы замечательно, если еще была возможность сразу несколько ботов запустить одновременно с 1 консоли

**Comment by elektrohouse0** [comment]
> Полностью согласен по поводу гибкой настройки бота, + ко всем выше описанным позициям. Было бы замечательно, если еще была возможность сразу несколько ботов запустить одновременно с 1 консоли.

**Comment by elektrohouse0** [comment]
Либо напишите подробно, как это сделать, желательно со скринами

**Comment by elektrohouse0** [comment]
I completely agree about the flexible configuration of the bot, + to all the positions described above. It would be great if it was still possible to launch several bots simultaneously from 1 console.

**Comment by Alexell** [comment]
@zv09 я вчера зашел в игру и обнаружил, что вся тема с тапами поменялась. Разработчики наконец сообразили, что тапы слишком малоприбыльны и исправили это дело. Я выкатил обновление тапов, но теперь под вопросом вся схема работы с паузой на час. Возможно на голосование нужно поднимать вопрос о реализации постоянных тапов. Тапаем, пока энергия не кончится, спим до восстановления энергии, снова тапаем и т.д. А основные действия изолируем от тапов, чтобы они запускались реже (пока еще не придумал, как лучше это сделать).

**Comment by Alexell** [comment]
> It would be great if it was still possible to launch several bots simultaneously from 1 console.

What do you mean? Several bots for different projects? If so, then there is no problem, I always have several running:
![изображение](https://github.com/user-attachments/assets/ae9e7e0f-8896-421d-9800-609d51f73c4f)

**Comment by khosrowkhazraei** [comment]
I 1 hour sleep is too much as the farmin is much faster, can we reduce it to 30 min or so?

**Comment by zv09** [comment]
> @zv09 я вчера зашел в игру и обнаружил, что вся тема с тапами поменялась. Разработчики наконец сообразили, что тапы слишком малоприбыльны и исправили это дело. Я выкатил обновление тапов, но теперь под вопросом вся схема работы с паузой на час. Возможно на голосование нужно поднимать вопрос о реализации постоянных тапов. Тапаем, пока энергия не кончится, спим до восстановления энергии, снова тапаем и т.д. А остальные действия изолируем от тапов, чтобы они запускались реже (пока еще не придумал, как лучше это сделать).

когда знакомился с этой поделкой, она еще на ipad работала, сейчас нет. Они постоянно меняют там код. 
на дроиде ставил кликер и он фигачил все утро до 11 пока спал. 
Потом обнаруживал красную надпись: too much taps, get a rest

Мы не знаем, собираются они ботов ограничивать от дропа или нет. Сейчас уже объявили что нет заходов в акк 15 дней и они его сжигают.
Отфильтровать логи перед дропом тоже могут и отсечь аккаунты на ботах.

 Смотри сам, как проще - Тапы пусть постоянны, но апгрейды например нет. 
 Человек же не может сутками тапать и играть. 
 Я предполагал что будет больше мимикрии под человеческое поведение. Хотя конечно бота по логам отфильтровать просто)

В идеале, чтобы вообще все вопросы снять - это симуляция ночного и дневного режима. 
Днем чел активный и постоянно заходит и тапает. 
Ночью спит и заходит раз в 3 часа по будильнику за бонусом.

**Comment by zv09** [comment]
> > It would be great if it was still possible to launch several bots simultaneously from 1 console.
> 
> What do you mean? Several bots for different projects? If so, then there is no problem, I always have several running: ![изображение](https://private-user-images.githubusercontent.com/25535043/356363430-ae9e7e0f-8896-421d-9800-609d51f73c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjQ4MTUsIm5iZiI6MTcyMzE2NDUxNSwicGF0aCI6Ii8yNTUzNTA0My8zNTYzNjM0MzAtYWU5ZTdlMGYtODg5Ni00MjFkLTk4MDAtNjA5ZDUxZjczYzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAwNDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNmQwNWZlYWEyMDZiNWNiMmExM2FmY2VjNzg0M2FmOTUyM2RkZWQzMWI2NzgwNjQ3NTFhZmMxMmRkYzdhMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dFkRFCgek1R8WmVPLkVB2pKtivWVy2XN-d_bgtWVEk)

у тебя на каждый бот свои сессии? 
чек хири как ферму сделали: один фреймворк  и один hash/api и там все боты пасутся через прокси кучей, нарефленные и просто синглы
https://github.com/TotalAwesome/BotFarmFactory

**Comment by zv09** [comment]
посмотрел твой профиль, норм ты продуктивный, еще музыку пишешь - респект) +

**Comment by Alexell** [comment]
> когда знакомился с этой поделкой, она еще на ipad работала, сейчас нет. Они постоянно меняют там код. на дроиде ставил кликер и он фигачил все утро до 11 пока спал. Потом обнаруживал красную надпись: too much taps, get a rest

Да, у них есть ежедневный лимит на добычу.
![изображение](https://github.com/user-attachments/assets/bc103e17-e59c-43c1-82db-f377556faac9)
Если делать тапы постоянными, нужно это учитывать.

> В идеале, чтобы вообще все вопросы снять - это симуляция ночного и дневного режима. Днем чел активный и постоянно заходит и тапает. Ночью спит и заходит раз в 3 часа по будильнику за бонусом.

А вот это мысль интересная. Днем действительно можно действовать как сейчас + постоянные тапы, а ночью - как сейчас, но с паузой в 3 часа и без постоянных тапов.

**Comment by Alexell** [comment]
> у тебя на каждый бот свои сессии?

Я не сторонник мультиаккаунтов. Я и так использую ботов, это нечестно по отношению к другим пользователям. Но я делаю это лишь для экономии своего времени. Так что у меня только один акк и есть еще тестовые, но их я использую только для разработки и тестирования. Что касается моего скрина с ботами, все они на одной сессии запущены, я один раз авторизовался в своем аккаунте и потом во все боты скопировал файл сессии и так все это уже не первый месяц работает. API_ID и API_HASH не нужно делать для каждого аккаунта. Кто вообще пустил этот дебильный слух?

> чек хири как ферму сделали: один фреймворк и один hash/api и там все боты пасутся через прокси кучей, нарефленные и просто синглы

Посмотрел, но как я уже сказал, мультиаккаунтами не интересуюсь, а с моим аккаунтом все боты на моем скрине прекрасно работают уже давно, у них у всех в `.env` одни и те же API_ID и API_HASH указаны. Я привык к такой схеме, слежу за обновами каждого бота и меня все устраивает.

**Comment by Alexell** [comment]
> посмотрел твой профиль, норм ты продуктивный, еще музыку пишешь - респект) +

Спасибо! Ох, когда я в последний раз музыку писал... К сожалению, IT и музыка для меня не совместимы. Если мне приходится постоянно писать код или делать другую работу в IT, я не могу писать музыку - мой мозг просто не может расслабиться и переключиться на творчество.

**Comment by Alexell** [comment]
> I 1 hour sleep is too much as the farmin is much faster, can we reduce it to 30 min or so?

As I wrote somewhere before, the current 1-hour sleep is not connected with taps and energy recovery. Previously, taps were useless, you couldn't earn much there. Now the logic in the game has been updated and you can earn money on taps, so I will update the bot logic. During the day, taps will be constant and the sleep time will be approximately the same as the energy recovery time (but slightly variable). Other actions will occur less often, approximately as now. And at night, as @zv09 suggested above, the bot will do all actions once every 3 hours.

**Comment by Quabro2** [comment]
> > Обновил папбку bots, и куда то тапы пропали в боте, перестал тапать короче, а сегодня походу подвезли обнову скилы по тапам, и бонус с тапанье, новая вклада добыча
> 
> все нормально тапает `2024-08-08 16:56:20 | SUCCESS | 308 | x | Earned money: +414 | Energy left: 5793`

А не подскажете почему бот перестал прокачивать основные навыки? прокачиваются только навыки для тапа и все, несколько дней назад все работало хорошо, бота обновил и теперь вот так.

**Comment by Quabro2** [comment]
@Alexell А не подскажете почему бот перестал прокачивать основные навыки? Прокачиваются только навыки для тапа и все, несколько дней назад все работало хорошо, бота обновил и теперь вот так.

**Comment by Alexell** [comment]
Not offtop!
