### ISSUE TITLE
Подключения сразу несколько аккаунтом

### ISSUE THREAD

**Issue by furzich2015** [Alexell/XEmpireBot#41]
Как мне подключить сразу несколько аккаунтов?
Нужно ли менять api_id и api_hash для входа на остальние аккаунты?
И как их вписывать в env, через кому или списком?

**Comment by sanyapg** [comment]
Примеры значений можно посмотреть в README. 
Реальные типы значений и как они задаются - в исходниках. 
Там всё описано.

**Comment by elektrohouse0** [comment]
> Как мне подключить сразу несколько аккаунтов? Нужно ли менять api_id и api_hash для входа на остальние аккаунты? И как их вписывать в env, через кому или списком?

Очень актуальный вопрос!

**Comment by elektrohouse0** [comment]
> > Примеры значений можно посмотреть в README. Реальные типы значений и как они задаются - в исходниках. Там всё описано.
> 
> К сожелению я не нашел информации стосовно того, как настроить мультиаккаунтинх. Если ты скажеш как, было бы супер если вы поделитесь.

Посмотри темы проблем, я там описал, думаю разберешься

**Comment by Alexell** [comment]
Что касается API_ID / API_HASH, вы можете создать их на каком-то одном аккаунте. Их не нужно создавать для каждого аккаунта.
Что касается дальнейших действий, то вот:
- Запустите бота.
- Выберите действие 1 - Create session, войдите в первый акк Telegram.
- Запустите бота еще раз, снова выберите действие 1 и войдите во второй акк Telegram.
- Запустите бота и выберите действие 2 - Run bot. Оба аккаунта будут использоваться автоматически.

**Крайне не рекомендуется запускать несколько аккаунтов без прокси.**

**Comment by elektrohouse0** [comment]
> Что касается API_ID / API_HASH, вы можете создать их на каком-то одном аккаунте. Их не нужно создавать для каждого аккаунта. Что касается дальнейших действий, то вот:
> 
> * Запустите бота.
> * Выберите действие 1 - Create session, войдите в первый акк Telegram.
> * Запустите бота еще раз, снова выберите действие 1 и войдите во второй акк Telegram.
> * Запустите бота и выберите действие 2 - Run bot. Оба аккаунта будут использоваться автоматически.
> 
> **Крайне не рекомендуется запускать несколько аккаунтов без прокси.**

1.Почему без прокси нельзя, что может произойти? 
2.если 1 бота с винды, а второго через виртуалку на Linux, можно обойтись без прокси?

**Comment by Alexell** [comment]
1. Я сказал "не рекомендуется", а не "нельзя". Создатели любого сайта или веб-приложения могут увидеть, что разные аккаунты авторизуются с одного и того же IP. Это конечно не является гарантией того, что они обратят на это внимание, поскольку существует NAT, но все же, с учетом того, что это бот, есть риски.
2. Нет, этот вариант не решит проблему, нужно чтобы на аккаунтах был разный **внешний IP**.

**Comment by elektrohouse0** [comment]
> 1. Я сказал "не рекомендуется", а не "нельзя". Создатели любого сайта или веб-приложения могут увидеть, что разные аккаунты авторизуются с одного и того же IP. Это конечно не является гарантией того, что они обратят на это внимание, поскольку существует NAT, но все же, с учетом того, что это бот, есть риски привлечь ненужное внимание создателей игры к своим аккаунтам.
> 2. Нет, этот вариант не решит проблему, нужно чтобы на аккаунтах был разный **внешний IP**.

Если из открытых источников брать? 
![Screenshot_20240808-232805](https://github.com/user-attachments/assets/2c8b1ea4-34da-49c6-985f-f0cd65560284)

Такого плана пойдет?

**Comment by Alexell** [comment]
Это ваше личное дело, какие прокси вы будете использовать. Возможность мультиаккаунтов и прокси в боте есть просто для галочки, иначе меня бы замучили. Я не приветствую это и не буду отвечать на вопросы по этой теме.

**Comment by furzich2015** [comment]
> Что касается API_ID / API_HASH, вы можете создать их на каком-то одном аккаунте. Их не нужно создавать для каждого аккаунта. Что касается дальнейших действий, то вот:
> 
> * Запустите бота.
> * Выберите действие 1 - Create session, войдите в первый акк Telegram.
> * Запустите бота еще раз, снова выберите действие 1 и войдите во второй акк Telegram.
> * Запустите бота и выберите действие 2 - Run bot. Оба аккаунта будут использоваться автоматически.
> 
> **Крайне не рекомендуется запускать несколько аккаунтов без прокси.**

Большое спасибо за ответ. Ввобщем я так и предполагал, он нужен только для авторизации самой сесии. Второй вопрос (возможно не по теме), как работать в кейсе, 1 аккаунт - 1 прокси. 1 сесия = 1 строка прокси? Или как-то по другому он ему относиться? Поскольку у меня всего 3 аккаунта, ето не проблема в общем (посколько несколько проектов спокойно относяться к 3 аккаунтам с одной IP - к примеру семья которая тапает^^), в дальнейшем хочу сделать ферму с 100 акк, по этому хорошо б знать как зделаеть статичнеску привязку 1 сесии только к 1 прокси. Спасибо.

**Comment by Alexell** [comment]
@furzich2015 всё совсем наоборот. Прокси нужен в первую очередь для самой игры, ну и для авторизации в тг конечно тоже. Не просто же так он прописывается в aiohttp и используется при каждом запросе. Это нужно чтобы не палиться создателям игры.
Насчет второго вопроса - ничего делать не надо, в боте все уже сделано. Добавьте свою пачку сессий и пачку прокси. Запустите бот. Он будет по очереди запускать сесссии с задержкой и для каждой сессии будет выбирать прокси из файла, так и будет, что 1 прокси для 1 сессии на все время работы с сессией (в пределах работы бота). При следующем запуске бота, скорее всего у сессий будут те же ip, если число сессий и ip не поменялось, т.к. он же грузит их в список одинаковой логикой, значит и выбирать будет в том же порядке, т.к. он прокси выбирает не рандомно, а по порядку.

**Comment by furzich2015** [comment]
> @furzich2015 всё совсем наоборот. Прокси нужен в первую очередь для самой игры, ну и для авторизации в тг конечно тоже. Не просто же так он прописывается в aiohttp и используется при каждом запросе. Это нужно чтобы не палиться создателям игры. Насчет второго вопроса - ничего делать не надо, в боте все уже сделано. Добавьте свою пачку сессий и пачку прокси. Запустите бот. Он будет по очереди запускать сесссии с задержкой и для каждой сессии будет выбирать прокси из файла, так и будет, что 1 прокси для 1 сессии на все время работы с сессией (в пределах работы бота). При следующем запуске бота, скорее всего у сессий будут те же ip, если число сессий и ip не поменялось, т.к. он же грузит их в список одинаковой логикой, значит и выбирать будет в том же порядке, т.к. он прокси выбирает не рандомно, а по порядку.

Большое спасибо за ответ. Все очень понятно!
