### ISSUE TITLE
Запуск несколько сессий одновременно-решение

### ISSUE THREAD

**Issue by elektrohouse0** [Alexell/XEmpireBot#42]
⬇⬇⬇После того как создали первую сессию⬇⬇⬇

$ git clone https://github.com/Alexell/XEmpireBot.git
$ cd XEmpireBot

# Windows (сначала установите Python 3.10 или более новую версию)
> python -m venv venv
> venv\Scripts\activate
> pip install -r requirements.txt
> copy .env-example .env
> # укажите ваши API_ID и API_HASH, остальное можно оставить по умолчанию
> python main.py

！！！Заходим в .env заменяем API_ID и API_HASH на другой аккаунт, и только после этого создаём 2-ую сессию и т.д.
！！！В строке SLEEP_BETWEEN_START= ОБЯЗАТЕЛЬНО! указывать значения в таком формате: [20,60]. С этим у меня лично возникла загвоздка, в итоге спустя 3 дня разобрался. Надеюсь кому помогу)

**Comment by Alexell** [comment]
Не надо дезинформацию распространять. API_ID и API_HASH не обязательно должны быть созданы на том же аккаунте, который вы авторизуете в боте.
