### ISSUE TITLE
Происходит проигрыш PVP по выигрышной стратегии

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Alexell/XEmpireBot#43]
![изображение](https://github.com/user-attachments/assets/0562fce6-5f13-40cb-a2b3-a13bb8c08981)

Как может flexible проигрывать protective? Это не соответствует правилам игры.
flexible должен проигрывать против agressive, и должен выигрывать против protective.

**Comment by Alexell** [comment]
На этот вопрос уже неоднократно отвечали, так в игре случается, я не знаю, почему. Я лишь выдаю результаты, которые мне выдала игра.

**Comment by Nord1cWarr1or** [comment]
> На этот вопрос уже неоднократно отвечали

Странно, перед созданием полистал иссуйки, не увидел

**Comment by Alexell** [comment]
#8 например

**Comment by Nord1cWarr1or** [comment]
Увидел, спасибо
