### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by seligor** [Alexell/XEmpireBot#45]
2024-08-09 23:37:29 | ERROR    | 755 | MuskEmpire | Unknown error: list index out of range
Traceback: Traceback (most recent call last):
  File "/home/seligor/bots/XEmpireBot/bot/core/bot.py", line 731, in run
    skill = calculate_best_skill(skills=self.dbs['dbSkills'], ignored_skills=config.IGNORED_SKILLS, profile=full_profile, level=self.level, balance=self.balance, improve=improve_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seligor/bots/XEmpireBot/bot/utils/functions.py", line 112, in calculate_best_skill
    best_skill = sorted(possible_skills, key=lambda x: x["ratio"])[-1]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by Alexell** [comment]
@seligor 
- Update the bot to the latest version (command: `git pull`)
- Set **DEBUG_MODE=True** in your .env
- Run the bot with MANDATORY redirection of stdout to a file: `venv/bin/python3 main.py --action 2 >> app.log 2>&1`
- Monitor the contents of `app.log` and wait for errors (ERROR) to appear, then stop the bot
- Attach your `app.log` here for analysis and troubleshooting

**Comment by seligor** [comment]
[app.log](https://github.com/user-attachments/files/16565786/app.log)
