### ISSUE TITLE
too many taps today, take some rest

### ISSUE THREAD

**Issue by seligor** [Alexell/XEmpireBot#46]
2024-08-09 23:38:32 | INFO     | 313 | MuskEmpire | Taps started
2024-08-09 23:38:36 | DEBUG    | 333 | MuskEmpire | Taps response:
{"success":false,"error":"too many taps today, take some rest"}
2024-08-09 23:38:43 | DEBUG    | 333 | MuskEmpire | Taps response:
{"success":false,"error":"too many taps today, take some rest"}

**Comment by Alexell** [comment]
Do you know what time the daily tap limit resets?

**Comment by seligor** [comment]
what if process this response and disable taps?

**Comment by Alexell** [comment]
This is not a problem. I even already found the tap limit and know it. But after stopping taps, I don't know when to turn them on again. And the tap limit (current) is shown only in requests that perform taps.

**Comment by Alexell** [comment]
Okay, to do it well, I'd better watch the game in the morning when the limit resets. Probably it can happen at 7:00 GMT, when the daily quests are reset.

**Comment by khosrowkhazraei** [comment]
And to randomize and humanize the intervals i think this logic will be better:

					# new logic for sleep
					current_hour = datetime.now().hour

					if 8 <= current_hour < 22:  # Day time (8 AM to 10 PM)
						# Randomize interval between 1200 and 1800 seconds
						sleep_time = random.randint(1200, 1800)
						log.info(f"{self.session_name} | Day Shift: Sleep {sleep_time // 60} min")
						await asyncio.sleep(sleep_time)
					else:  # Night time (10 PM to 8 AM)
						log.info(f"{self.session_name} | Night Shift: Sleep 3 hours")
						await asyncio.sleep(10800)  # Sleep for 3 hours (10800 seconds)
						self.authorized = False

**Comment by Alexell** [comment]
@khosrowkhazraei offtop. This will be done next week.
