### ISSUE TITLE
Quiz / Rebus of the Day / Youtube tasks

### ISSUE THREAD

**Issue by zv09** [Alexell/XEmpireBot#47]
Бот не закрывает сейчас эти ежесуточные загадки? 
У тебя вроде карточки с сайта берутся. 
Ответы на загадку и ребус тоже в пабликах есть, их сложно добавить к инвестициям и заданиям по Youtube?..

upd. посомтрел json c ответами, вижу там ответ на загадку, но она не подходит, видимо они ее уже меняют на следующую. 
а по ответом на youtube просмотры что то планируется?

**Comment by Alexell** [comment]
Ребус работает. Я думал, что загадки тоже, но оказалось, что в игре поменялось опять все, загадки нужно отправлять по другой логике, как ребус и проверять в другом месте. Я не успеваю за изменениями в игре :D По крайней мере мне больше не придется загадки заполнять, только фонды.

> вижу там ответ на загадку, но она не подходит
Все там подходит, можешь найти каналы с ответами на загадки и сравнить, там все правильно. Впрочем, теперь это не важно, т.к. ответы извне не требуются.

**Comment by Alexell** [comment]
Фикс для загадок выкачу чуть позже. Квесты по ютубу я делать не собираюсь.
