### ISSUE TITLE
Unknown error: 'CryptoBot' object has no attribute 'level'

### ISSUE THREAD

**Issue by FaxWeb7** [Alexell/XEmpireBot#48]
спамит ошибкой | ERROR    | 784 - 7_ghorik | Unknown error: 'CryptoBot' object has no attribute 'level'

**Comment by zv09** [comment]
акк в игре новый или прокачанный немного?

**Comment by FaxWeb7** [comment]
софт уже больше недели стоит на акках, прокачанный

**Comment by zv09** [comment]
вроде всё нормально пушит посты и парсит реквесты... 
может git pull сделать... апдейт же был на днях и у бота апдейт был

**Comment by FaxWeb7** [comment]
не, последний изменения стянуты. Дебаг мод включил, ошибка в коде видимо действительно имеется, в 553 строке bot.py, где ```if level > self.level``` (откуда self.level, если он не был обьявлен в конструкторе класса)


<img width="1008" alt="Снимок экрана 2024-08-10 в 19 33 34" src="https://github.com/user-attachments/assets/760334c6-843c-4001-922d-30bc0e104b55">

**Comment by Alexell** [comment]
Нет там никакой ошибки. self.update_level выполняется только когда есть соответствующий аттрибут класса, иначе он прописывается (см. строки 587 - 590).

**Comment by FaxWeb7** [comment]
короче для себя я это пофиксил, поменял 566 строку на ```proxy_conn = aiohttp.TCPConnector(verify_ssl=False)```.
Появилась новая ошибка 
```
2024-08-10 13:41:40 | ERROR    | 784 - 19_tima | Unknown error: 'dailyRewards'
Traceback: Traceback (most recent call last):
  File "/root/main-telegram-autoclickers/7_muskempire/bot/core/bot.py", line 611, in run
    daily_rewards = full_profile['data']['dailyRewards']
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'dailyRewards'
```
посмотрел json с профиля, с префиксом dailyReward там я нашел только это: 
```"dailyRewardLastDate":"2024-08-09 23:21:40","dailyRewardLastIndex":4```

**Comment by Alexell** [comment]
А это уже из-за обновления игры, которое они сделали сегодня. Ждите.
