### ISSUE TITLE
Зависание (похоже на бесконечный цикл)

### ISSUE THREAD

**Issue by PePaRiTB** [Alexell/XEmpireBot#51]
Привет!

После последней обновы через пару минут бот зависает и даже не реагирует на ctrl - c, только спустя секунд 10.
Видимо где-то идет зацикливание, дебаг сообщения ничего не показывают, ошибок тоже нет.
Но заметил, что чаще всего зависает после сообщения после прокачки скила

**Comment by madest18** [comment]
по ходу бот натыкается на задержку, по времени, обновления на следующий уровень и дальше не идет..
как временное решение, поставить чтобы обновлялось по 2 навыка за круг, у меня работает.

**Comment by beetlejuicerus** [comment]
Тоже самое, качает 1-2 скила и виснет

**Comment by PePaRiTB** [comment]
По тестил еще чутка, ошибка появляется когда у скила есть кд на прокачку (а остальные с друзьями), видимо все скилы на кд и бот не знает, что качать и начинает зацикливаться. Это проявляется на первом запущеном аке

**Comment by Alexell** [comment]
Бот учитывает и необходимых друзей и необходимые уровни других скилов и кд. Но вот я посмотрел щас, теоретически он и правда может зависать в цикле прокачки (не поиска лучшего скила). Хотя у меня такого нет. У меня не качает скилы профита уже 3-й день вообще, я пока не разбирался, почему. При этом, бот не зависает.
