### ISSUE TITLE
pls help to improve the .env configuration

### ISSUE THREAD

**Issue by SmILeTheMobster** [Alexell/XEmpireBot#52]
Hi everyone, I just discovered clickbots. I would like to ask for your help to find the most optimal and "safe" config, because I'm afraid that I can set it wrong and get banned.

**Comment by Bosonogij** [comment]
Александр спасибо за команду git pull а то я все время сносил систему для установки обновления, бот работает замечательно , но подскажи пожалуйста что вписать в SLEEP_BETWEEN_START чтобы бот не через час а полчаса запускал серию заново?

**Comment by zv09** [comment]
> Александр спасибо за команду git pull а то я все время сносил систему для установки обновления, бот работает замечательно , но подскажи пожалуйста что вписать в SLEEP_BETWEEN_START чтобы бот не через час а полчаса запускал серию заново?

это уже обсуждали [тут](https://github.com/Alexell/XEmpireBot/issues/40)

**Comment by Alexell** [comment]
@Bosonogij да, для обновления бота, тебе нужно просто перейти в директорию бота и выполнить `git pull`. Можно конечно предварительную проверку сделать `git fetch`, но это не обязательно. Однако, тут важно понимать, если вдруг ты сделал локальные изменения, например вчера, когда игра перестала авторизовывать по старому юзернейму и ты в скрипте прописал новый, а потом я выкатил обнову с тем же самым и любые другие обновы, то в таком случае, прежде, чем обновиться, тебе нужно сбросить локальные изменения командой `git reset --hard`.

Что же касается `SLEEP_BETWEEN_START`, то этот параметр не имеет ничего общего с тем, о чем вы говорите. Читайте внимательно README. Там сказано: "Задержка перед запуском каждой сессии". Этот параметр нужен только тогда, когда вы используете сразу несколько сессий (телеграм аккаунтов).

Задержкой основного цикла нельзя управлять. Если вас беспокоят тапы, то новая логика, которую я выкатил вчера, выполняет тапы постоянно с задержкой на восстановление энергии, а остальные действия примерно каждый час, как раньше. Но это только в дневное время. В ночное время теперь все действия выполняются раз в 3 часа.

**Comment by Alexell** [comment]
@SmILeTheMobster there is no single configuration that works for everyone, as some parameters need to be adjusted as your hero levels up.

If you want to use the bot as safely as possible, first make sure to update the bot to get yesterday's update, as it includes humanized intervals that consider both day and night time. As for the configuration, just avoid setting values that are too large. Most parameters can be left at their default settings. However, you can set them approximately like this:
```
TAPS_ENABLED=True
TAPS_PER_SECOND=[10,20]
PVP_ENABLED=True
PVP_LEAGUE=auto
PVP_UPGRADE_LEAGUE=
PVP_STRATEGY=random
PVP_COUNT=5
SKILLS_COUNT=
IGNORED_SKILLS=
MINING_SKILLS_LEVEL=10 # here specify as you need
PROTECTED_BALANCE=10000000 # here specify as you need

SLEEP_BETWEEN_START=
ERRORS_BEFORE_STOP=
USE_PROXY_FROM_FILE=
DEBUG_MODE=False
```
