### ISSUE TITLE
Всё поломалось...

### ISSUE THREAD

**Issue by ilya125625262** [Alexell/XEmpireBot#56]
![capture_20240812200412031](https://github.com/user-attachments/assets/2c08919a-fb84-439f-863c-20f90864ef7c)

**Comment by Agor71** [comment]
Требуется только сменить имя бота игры в bot.py в 49 и 50 строках.
Актуальное имя бота — 'empirebot'

**Comment by ilya125625262** [comment]
> Требуется только сменить имя бота игры в bot.py в 49 и 50 строках. Актуальное имя бота — 'empirebot'.
> 
> P.S. Проверил на себе, после смены всё заработало.

Действительно сработало. 
Огромное спасибо!
