### ISSUE TITLE
new changes needed

### ISSUE THREAD

**Issue by cr4zyfish** [Alexell/XEmpireBot#57]
the api url should be changed to https://api.muskempire.io because https://api.xempire.io is not responding. the bot name should be changed to empirebot instead of muskempire_bot

**Comment by Alexell** [comment]
![изображение](https://github.com/user-attachments/assets/d6417bb0-3bd1-433d-b1c1-5648d4da6fff)
The api address has not changed and works. But it does not allow authorization with the old username, although in fact the username is working.
