### ISSUE TITLE
Username not found: muskempire_bot

### ISSUE THREAD

**Issue by Pawansingh333** [Alexell/XEmpireBot#58]
Username not found: muskempire_bot please fix

**Comment by cr4zyfish** [comment]
open bot.py file and rename muskempire_bot to empirebot

**Comment by bowler14** [comment]
go to bot>core>bot.py Then change username that highlighted 

![image](https://github.com/user-attachments/assets/10764a18-549c-431d-a65d-9f54933256e1)
