### ISSUE TITLE
Закрыли доступ к апи БД?

### ISSUE THREAD

**Issue by Visualua** [Alexell/XEmpireBot#60]
2024-08-13 08:54:17 | ERROR | 76 | ClausSanta | Authorization error: database is locked

**Comment by Alexell** [comment]
Это ошибка Pyrogram, означающая, что сессия заблокирована (т.е. уже используется). Убедитесь, что только один софт бота использует физический файл .session и что вы случайно не запустили две копии бота.

**Comment by Alexell** [comment]
В крайнем случае, перезагрузите ваш ПК/сервер и запутите бота снова.

**Comment by Visualua** [comment]
Да, уже нашел. Запускаю через веб панель бота с хайдом самого окна. И при перезапуске почему-то не закрылся в этот раз старый процесс. Спасибо за помощь
