### ISSUE TITLE
Unknown error: 'CryptoBot' object has no attribute 'level'

### ISSUE THREAD

**Issue by madest18** [Alexell/XEmpireBot#61]
2024-08-13 11:38:04 | DEBUG    | 142 | tg5 | Sync profile response:
{"success":true,"data":{"hero":{"id":7261582408,"level":19,"exp":20373431750,"money":597462040,"moneyUpdateDate":"2024-08-13 08:38:03","lastOfflineBonusDate":"2024-08-13 08:38:03","moneyPerHour":518389000,"energyUpdateDate":"2024-08-13 08:38:03","tax":20,"pvpMatch":226,"pvpWin":99,"pvpLose":127,"pvpMatchesDaily":0,"pvpMatchesDailyDay":null,"earns":{"task":{"moneyPerTap":396,"limit":125000,"energy":125000,"recoveryPerSecond":220,"bonusChance":14.4,"bonusMultiplier":2.1000000000000001}},"dailyRewardLastDate":"2024-08-13 07:27:40","dailyRewardLastIndex":9,"onboarding":["19999","9010","10020","10460","9020","10015","41","10000","10055","40","10080","10700","10800","10040","1","10720","10320","10050","9030","10010"],"updateDate":"2024-07-24 21:21:09.782195","userId":7261582408}}}
2024-08-13 11:38:04 | ERROR    | 856 | tg5 | Unknown error: 'CryptoBot' object has no attribute 'level'
Traceback: Traceback (most recent call last):
  File "/root/MuskEmpireBot/bot/core/bot.py", line 608, in run
    self.update_level(level=int(profile['hero']['level'] or 0))
  File "/root/MuskEmpireBot/bot/core/bot.py", line 548, in update_level
    if level > self.level:
AttributeError: 'CryptoBot' object has no attribute 'level'

наверное такая проблема не только у меня... )

**Comment by Alexell** [comment]
Ну, вы второй с такой проблемой. Первый запускал бот через другой софт, который видимо управлял сразу несколькими ботами, я за такие вещи не отвечаю. У вас, подозреваю, тоже не чистый мой бот в том виде, в каком он в находится в репозитории, иначе у вас не было бы этой ошибки.

Остановите бота, переместите папку `sessions` и файл `.env` на уровень выше (в `/root`), перейдите в `/root`, удалите папку MuskEmpireBot и выполните корректный процесс скачивания и установки бота с нуля по инструкции в readme. Затем поместите в него `sessions` и файл `.env` и можете запускать. Кроме того, если сделаете это, сможете без проблем обновляться с помощью `git pull`.

**Comment by madest18** [comment]
git pull у меня проходит без проблем, так же ничего не подменялось...
бот работает с момента, когда репа называлась еще MuskEmpireBot и все было прекрасно...
перешел с socks5 на простой http и проблема вроде ушла..
тикет можно закрыть.
