### ISSUE TITLE
почему то ничего не происходит когда нажимаю создать сессию 

### ISSUE THREAD

**Issue by Aressergeevich** [Alexell/XEmpireBot#66]
запускаю бота, нажимаю создать сессию но дальше ничего не идет
![image](https://github.com/user-attachments/assets/6fa66a5f-edeb-48c8-bcdf-4dcc67792780)

**Comment by 0y-a0** [comment]
тоже самое

**Comment by Alexell** [comment]
Я не могу ничего подсказать в данной ситуации, это касается Pyrogram. У меня все работает и в других Pyrogram проектах я не сталкивался с подобной проблемой. Могу посоветовать только убедиться что вы установили все зависимости по инструкции в readme и поставить Python 3.10. Хотя бот нормально работает и на 3.11 и на 3.12, но я проверял только на Linux, я не использую Python на Windows.

**Comment by 0y-a0** [comment]
> запускаю бота, нажимаю создать сессию но дальше ничего не идет
> ![image](https://github.com/user-attachments/assets/6fa66a5f-edeb-48c8-bcdf-4dcc67792780)
> 

Смотри как я решил. Точнее я много чего пробовал и отбросил идею локально у себя его запустить. Вместо этого можно использовать допустим Google Colab, там просто запустить с гит клон и тд этого бота и можно легко создать сессию, которую можно скачать оттуда и переместить куда угодно и запустить с твоей сессией. Запустить ты можешь хоть на том же гугл колаб

**Comment by GetHighFive789** [comment]
Путём перебора всех версий питон, остановился на 3.10.11 (32 bit)
Обновив pip до 24 версии на ней запустились все нужные мне боты.
