### ISSUE TITLE
Увеличение суммы инвестиций в фонд

### ISSUE THREAD

**Issue by PePaRiTB** [Alexell/XEmpireBot#68]
Добрый день! Сейчас инвестирует среднюю величину, а хотелось бы по максимуму (х2 от текущей суммы) Возможно, надо пересмотреть алгоритм расчета инвестиции

**Comment by PePaRiTB** [comment]
вот как у другого бота сделан расчет ставки:
https://github.com/paveL1boyko/MuskEmpireBot/blob/main/bot/core/api_js_helpers/bet_counter.py

**Comment by Alexell** [comment]
Бот инвестирует самую большую сумму, которая вам доступна (так же, как если вы в игре ползунок передвинете вправо на максимум). Если не хватает денег, тогда бот уже начинает уменьшать сумму ставки.
