### ISSUE TITLE
Решение YT заданий 

### ISSUE THREAD

**Issue by PePaRiTB** [Alexell/XEmpireBot#69]
Добрый день! У другого бота есть возможность выполнения заданий по ютубу, но переходить не хочется. Может сделаем похожее решение?

Ссылка: https://github.com/paveL1boyko/MuskEmpireBot/blob/main/bot/core/bot.py#L85
Функция execute_and_claim_daily_quest

Коды с видосами:
https://github.com/paveL1boyko/MuskEmpireBot/blob/main/youtube.json

**Comment by Alexell** [comment]
Я уже в каком-то Issue писал, что не буду делать этот функционал.
Во первых, мне хватает ежедневного заполнения фондов. Следить и добавлять новые коды мне некогда.
Во вторых, делать этот функционал просто нет смысла, за просмотр видео лишь дают немного денег на баланс.

Если в `dbData` игры вдруг появятся коды для видео (как ответы на ребус и загадку), тогда сделаю.

**Comment by Alexell** [comment]
Я уже в каком-то Issue писал, что не буду делать этот функционал.
Во первых, мне хватает ежедневного заполнения фондов. Следить и добавлять новые коды мне некогда.
Во вторых, делать этот функционал просто нет смысла, за просмотр видео лишь дают немного денег на баланс.

Если в `dbData` игры вдруг появятся коды для видео (как ответы на ребус и загадку), тогда сделаю.

**P.S.** Если вы хотите перейти на бота, "автор" которого, взял его у меня, не оформил как форк и нигде не указал, что это мой бот, то как бы мне не о чем с вами говорить вообще.
