### ISSUE TITLE
Бот не прокачивает скилы, только собирает прибыль

### ISSUE THREAD

**Issue by elektrohouse0** [Alexell/XEmpireBot#73]
Столкнулся с 2 проблемами, спустя пару суток бот перестаёт прокачивать скилы, только собирает прибыль, при этом не выполняет задания. В данный момент пруФА НЕТ. Как только замучу проблемы, добавлю лог

**Comment by Alexell** [comment]
Жду полный `app.log`

**Comment by zv09** [comment]
может френдов не хватает, если акк голый без френдов, то акк встает колом на 18 уровне и может только mining качать

**Comment by GetHighFive789** [comment]
> Столкнулся с 2 проблемами, спустя пару суток бот перестаёт прокачивать скилы, только собирает прибыль, при этом не выполняет задания. В данный момент пруФА НЕТ. Как только замучу проблемы, добавлю лог

У меня так же. Просто перезапускаю бота раз в день.

**Comment by Alexell** [comment]
Поставил тестировать на акке без рефералов, но уверен, что бот без проблем будет тапать, играть в PvP, прокачивать все скилы, какие сможет (когда доступных не останется, он просто не будет этого делать), решать ребус, загадку, инвестировать и прочее.

**Comment by Alexell** [comment]
Топик закрываю. Тестирование длилось 4 суток. Логика бота работала нормально, все свои действия бот выполнял, как положено, скилы так же прокачивались по мере их доступности, последний сегодня рано утром. За 4 суток было небольшое количество ошибок, но это ошибки со стороны сервера игры: 500, 502, 524. Работа бота за 4 суток штатная.
[app.log](https://github.com/user-attachments/files/16846607/app.log) (если кому интересно)
