### ISSUE TITLE
Выполнение квестов с fakeCheck

### ISSUE THREAD

**Issue by PePaRiTB** [Alexell/XEmpireBot#78]
Привет! В dbQuests есть квесты, у которых фейковая проверка, их можно поставить на выполнение.
Например, квест blum или подписаться на аккаунт Х

Сможем сделать?

**Comment by Alexell** [comment]
Смочь то сможем, только зачем? За квесты на баланс немного капает и все, зачем ради этого тратить время, если это проект, в котором баланс на листинге не будет играть роли?

**Comment by PePaRiTB** [comment]
кажется, что в эти квестах могут быть те, которые будут влиять на дополнительный дроп. Например, blum. Чисто гипотеза. Ну и прокачка побыстрее пойдет у новых акков

**Comment by Alexell** [comment]
Ладно, сделаю, как будет время.

**Comment by SmILeTheMobster** [comment]
> Ладно, сделаю, как будет время.

а разве выполнение квестов не будет дополнительным плюсиком для акка, чтобы не отлететь?
