### ISSUE TITLE
data json forbidden

### ISSUE THREAD

**Issue by furzich2015** [Alexell/XEmpireBot#79]
![image](https://github.com/user-attachments/assets/7c00bcc8-5a97-440b-9b47-bf597634ecfd)
У меня одного такое?

**Comment by Alexell** [comment]
Я закрыл доступ к этому файлу, бот получает данные теперь через php скрипт и там всё работает. Но там такая же подпись запросов, как для игры, так что через браузер никак не посмотреть. См. cc9781520d3969a13bf99b33b19d4862991d96ee

P.S. Я не заполнил за 21 число, вылетело из головы. В readme написано, что я "постараюсь" заполнять каждый день. Я этого не гарантирую.
