### ISSUE TITLE
После ввода названия сессии код зависает навсегда

### ISSUE THREAD

**Issue by 0y-a0** [Alexell/XEmpireBot#82]
Клиент пирограма не работает почему то. Когда его вызывают,то код крашится чтоли, ничего не происходит.
Но и ошибок нет никаких. Зависимости скачаны понятно. Использую повершелл, пайтон версии 3.11.2. В чем может быть проблема?

**Comment by 0y-a0** [comment]
> Я не могу ничего подсказать в данной ситуации, это касается Pyrogram. У меня все работает и в других Pyrogram проектах я не сталкивался с подобной проблемой. Могу посоветовать только убедиться что вы установили все зависимости по инструкции в readme и поставить Python 3.10. Хотя бот нормально работает и на 3.11 и на 3.12, но я проверял только на Linux, я не использую Python на Windows.

Я решил вроде как. Только можете подсказать как работает регистрация. По каким параметрам берется акаунт на котором будет работать бот? По айди и хеш или по номеру который потом вводится при регистрации? И зачем в таком случае нужен айди и хеш и кстати когда вводишь токен бота,оно же не работает,да? Спасибо заранее за ответ

**Comment by Alexell** [comment]
`tgWebAppData` как параметры авторизации принимают только боты, созданные теми, кто не умеет делать полноценную авторизацию Telegram. Поищите нормальные популярные боты для проектов Hamster, Blum, MemeFi и других, вы увидите, что все они сделаны, так же, как и этот. Точнее даже наоборот, это я делаю свои боты по примеру уже известных, чтобы пользователям было проще. Кроме того, в некоторых проектах, данные `tgWebAppData` становятся невалидны через какое-то время, это так себе метод. Полноценные же боты, подобные этому, могут работать по несколько дней без остановки и проблем.

Поскольку любой софт с авторизацией в Telegram аккаунтах является неофициальным клиентом, его нужно зарегистрировать, поэтому вы идете на сайт Telegram, создаете там приложение и получаете `API_ID` и `API_HASH`. Это стандартная процедура Telegram. Если вы собираетесь добавить в бота несколько аккаунтов, вам не нужно делать `API_ID` и `API_HASH` на каждом из них. Вам просто один раз нужно создать приложение и вы сможете использовать эти `API_ID` и `API_HASH` и в моих ботах и в ботах от других авторов для других проектов, не зависимо от кол-ва ваших аккаунтов. Вам просто нужно прописывать `API_ID` и `API_HASH` в `.env` бота, чтобы он мог работать.

Что касается аккаунта, на котором бот будет играть в X Empire, то это вы уже сами решаете. Выбираете Create Session при запуске и авторизуете нужный вам аккаунт, как в обычном официальном клиенте. При необходимости, вы можете авторизовать несколько аккаунтов и бот будет играть сразу на всех. Но в таком случае, вам лучше купить прокси и прописать в файл `proxies.txt`, чтобы уменьшить риск палева создателями X Empire.

**Comment by Alexell** [comment]
Да, и напишите пожалуйста в #66 как решили проблему, там человеку тоже помощь нужна.

**Comment by 0y-a0** [comment]
Спасибо большое> `tgWebAppData` как параметры авторизации принимают только боты, созданные теми, кто не умеет делать полноценную авторизацию Telegram. Поищите нормальные популярные боты для проектов Hamster, Blum, MemeFi и других, вы увидите, что все они сделаны, так же, как и этот. Точнее даже наоборот, это я делаю свои боты по примеру уже известных, чтобы пользователям было проще. Кроме того, в некоторых проектах, данные `tgWebAppData` становятся невалидны через какое-то время, это так себе метод. Полноценные же боты, подобные этому, могут работать по несколько дней без остановки и проблем.
> 
> Поскольку любой софт с авторизацией в Telegram аккаунтах является неофициальным клиентом, его нужно зарегистрировать, поэтому вы идете на сайт Telegram, создаете там приложение и получаете `API_ID` и `API_HASH`. Это стандартная процедура Telegram. Если вы собираетесь добавить в бота несколько аккаунтов, вам не нужно делать `API_ID` и `API_HASH` на каждом из них. Вам просто один раз нужно создать приложение и вы сможете использовать эти `API_ID` и `API_HASH` и в моих ботах и в ботах от других авторов для других проектов, не зависимо от кол-ва ваших аккаунтов. Вам просто нужно прописывать `API_ID` и `API_HASH` в `.env` бота, чтобы он мог работать.
> 
> Что касается аккаунта, на котором бот будет играть в X Empire, то это вы уже сами решаете. Выбираете Create Session при запуске и авторизуете нужный вам аккаунт, как в обычном официальном клиенте. При необходимости, вы можете авторизовать несколько аккаунтов и бот будет играть сразу на всех. Но в таком случае, вам лучше купить прокси и прописать в файл `proxies.txt`, чтобы уменьшить риск палева создателями X Empire.

**Comment by 0y-a0** [comment]
Спасибо большое > `tgWebAppData` как параметры авторизации принимают только боты, созданные теми, кто не умеет делать полноценную авторизацию Telegram. Поищите нормальные популярные боты для проектов Hamster, Blum, MemeFi и других, вы увидите, что все они сделаны, так же, как и этот. Точнее даже наоборот, это я делаю свои боты по примеру уже известных, чтобы пользователям было проще. Кроме того, в некоторых проектах, данные `tgWebAppData` становятся невалидны через какое-то время, это так себе метод. Полноценные же боты, подобные этому, могут работать по несколько дней без остановки и проблем.
> 
> Поскольку любой софт с авторизацией в Telegram аккаунтах является неофициальным клиентом, его нужно зарегистрировать, поэтому вы идете на сайт Telegram, создаете там приложение и получаете `API_ID` и `API_HASH`. Это стандартная процедура Telegram. Если вы собираетесь добавить в бота несколько аккаунтов, вам не нужно делать `API_ID` и `API_HASH` на каждом из них. Вам просто один раз нужно создать приложение и вы сможете использовать эти `API_ID` и `API_HASH` и в моих ботах и в ботах от других авторов для других проектов, не зависимо от кол-ва ваших аккаунтов. Вам просто нужно прописывать `API_ID` и `API_HASH` в `.env` бота, чтобы он мог работать.
> 
> Что касается аккаунта, на котором бот будет играть в X Empire, то это вы уже сами решаете. Выбираете Create Session при запуске и авторизуете нужный вам аккаунт, как в обычном официальном клиенте. При необходимости, вы можете авторизовать несколько аккаунтов и бот будет играть сразу на всех. Но в таком случае, вам лучше купить прокси и прописать в файл `proxies.txt`, чтобы уменьшить риск палева создателями X Empire.

**Comment by 0y-a0** [comment]
Спасибо большое
 > `tgWebAppData` как параметры авторизации принимают только боты, созданные теми, кто не умеет делать полноценную авторизацию Telegram. Поищите нормальные популярные боты для проектов Hamster, Blum, MemeFi и других, вы увидите, что все они сделаны, так же, как и этот. Точнее даже наоборот, это я делаю свои боты по примеру уже известных, чтобы пользователям было проще. Кроме того, в некоторых проектах, данные `tgWebAppData` становятся невалидны через какое-то время, это так себе метод. Полноценные же боты, подобные этому, могут работать по несколько дней без остановки и проблем.
> 
> Поскольку любой софт с авторизацией в Telegram аккаунтах является неофициальным клиентом, его нужно зарегистрировать, поэтому вы идете на сайт Telegram, создаете там приложение и получаете `API_ID` и `API_HASH`. Это стандартная процедура Telegram. Если вы собираетесь добавить в бота несколько аккаунтов, вам не нужно делать `API_ID` и `API_HASH` на каждом из них. Вам просто один раз нужно создать приложение и вы сможете использовать эти `API_ID` и `API_HASH` и в моих ботах и в ботах от других авторов для других проектов, не зависимо от кол-ва ваших аккаунтов. Вам просто нужно прописывать `API_ID` и `API_HASH` в `.env` бота, чтобы он мог работать.
> 
> Что касается аккаунта, на котором бот будет играть в X Empire, то это вы уже сами решаете. Выбираете Create Session при запуске и авторизуете нужный вам аккаунт, как в обычном официальном клиенте. При необходимости, вы можете авторизовать несколько аккаунтов и бот будет играть сразу на всех. Но в таком случае, вам лучше купить прокси и прописать в файл `proxies.txt`, чтобы уменьшить риск палева создателями X Empire.

**Comment by 0y-a0** [comment]
> Да, и напишите пожалуйста в #66 как решили проблему, там человеку тоже помощь нужна.

Надеюсь подсказал, только у меня последний вопрос, когда сессию создавать с помощью токена бота, то как оно должно работать, если прав нету у бота, или оно работает у всех?
