### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by mlcni** [Alexell/XEmpireBot#83]
2024-08-23 13:14:40 | ERROR    | 856 | mthX1 | Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://alexell.ru')
Traceback: Traceback (most recent call last):
  File "C:\XEmpire\mthX1\bot\core\bot.py", line 744, in run
    helper = await self.get_helper()
  File "C:\XEmpire\mthX1\bot\core\bot.py", line 469, in get_helper
    response_json = await response.json()
  File "C:\XEmpire\XEmpireBot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://alexell.ru')

**Comment by Alexell** [comment]
Обновили бот? Ошибка пропала?

**Comment by GetHighFive789** [comment]
Уважаемый разработчик! Подскажите пожалуйста пару команд для windows.
1) команда для запуска бота в трей.
2) команда для запуска бота в полностью развернутом окне.
3) какой командой можно выбрать версию питон до установки связей? Не все боты требуют одну и ту же версию.
4) уточнение по git pull. Возможно ли без костылей настроить автообновление? Чтобы закрывался процесс, обновлялся бот, запускался бот. Хотя бы просто бат файл, который будет запускаться раз 6 часов и проделывать это, вдруг бот обновился на сайте.

Заранее благодарю за ответ. Еще вчера не знал что такое python…

**Comment by mlcni** [comment]
> Обновили бот? Ошибка пропала?

Вновь скачала бота, установил Анаконду с 3.10 Патоном, в Анаконде сделал отдельное окружение для бота, установил туда модули из реквайрментс бота. теперь запускаю ботов из Анаконды - всё норм работает.

**Comment by GetHighFive789** [comment]
> > Обновили бот? Ошибка пропала?
> 
> Вновь скачала бота, установил Анаконду с 3.10 Пайтоном, в Анаконде сделал отдельное окружение для бота, установил туда модули из реквайрментс. Теперь запускаю ботов из Анаконды - всё норм работает.

Спасибо за идею. Попробую на сервере так сделать. Пока что на нём не получалось запустить.

**Comment by mlcni** [comment]
> > > Обновили бот? Ошибка пропала?
> > 
> > 
> > Вновь скачала бота, установил Анаконду с 3.10 Пайтоном, в Анаконде сделал отдельное окружение для бота, установил туда модули из реквайрментс. Теперь запускаю ботов из Анаконды - всё норм работает.
> 
> Спасибо за идею. Попробую на сервере так сделать. Пока что на нём не получалось запустить.

Из плюсов: ставишь окружение 1 раз и при необходимости можно обновить модули в Анаконде, тоже 1 раз на всех ботов. Из минусов: приходиться запускать бота из командной строки, я ввожу три строки команд.

**Comment by GetHighFive789** [comment]
> > > > Обновили бот? Ошибка пропала?
> > > 
> > > 
> > > Вновь скачала бота, установил Анаконду с 3.10 Пайтоном, в Анаконде сделал отдельное окружение для бота, установил туда модули из реквайрментс. Теперь запускаю ботов из Анаконды - всё норм работает.
> > 
> > 
> > Спасибо за идею. Попробую на сервере так сделать. Пока что на нём не получалось запустить.
> 
> Из плюсов: ставишь окружение 1 раз и при необходимости можно обновить модули в Анаконде, тоже 1 раз на всех ботов. Из минусов: приходиться запускать бота из командной строки, я ввожу три строки команд.

С анакондой разобрался. Но, на сервере дело дальше создания файла сессии не идёт. Не хочу больше рабочий сервер ковырять. Куплю другой сервер специально под ботов. Конечно же с денег с dogs)))

**Comment by Alexell** [comment]
@GetHighFive789 у меня нет и не будет Python на Windows, только на Linux. Поэтому не все могу подсказать. Что касается ботов, все боты, насколько мне известно, требуют Python 3.10 и не все поддерживаются на версиях выше, ставить лучше сразу 3.10. А что касается зависимостей, то в readme все написано, нужно использовать виртуальное окружение. В папке с каждым ботом грубо говоря будет папка со всеми зависимостями и так они не будут конфликтовать, если версии пакетов разные. В любом случае, если вы уже используете Anaconda, как вам посоветовали, это уже не важно. Но сервак лучше берите на линуксе. Если ботов не очень много, то хватит vps за 200-250р/мес, но это всё уже не нужный мне оффтоп.
