### ISSUE TITLE
ERROR    

### ISSUE THREAD

**Issue by Smerch19** [Alexell/XEmpireBot#84]
2024-08-23 15:36:03 | ERROR    | 532 | Firs_ses_Maks_HK | Get helper error: 403 Forbidden (contact Alexell to solve this issue)

**Comment by Alexell** [comment]
It looks like you used someone else's bot, which used my data for investing without permission. All IP addresses with unsuccessful requests have been blocked. If you use my bot, send me the external IP where the bot works, I will unblock it.

**Comment by Smerch19** [comment]
Perhaps this error occurred because I am using Proton VPN?

**Comment by Smerch19** [comment]
> It looks like you used someone else's bot, which used my data for investing without permission. All IP addresses with unsuccessful requests have been blocked. If you use my bot, send me the external IP where the bot works, I will unblock it.

I didn’t use other bots, I opened the link in the get_helper function...

IP: 89.39.106.222

**Comment by Alexell** [comment]
Server-side validation has been updated (became slightly softer). All IP addresses blocked after 2024-08-22 05:48 GMT have been unblocked.
