### ISSUE TITLE
[400 YOU_BLOCKED_USER]

### ISSUE THREAD

**Issue by Ba4ana** [Alexell/XEmpireBot#85]
| ERROR    | 77 | xempire | Authorization error: Telegram says: [400 YOU_BLOCKED_USER] - You blocked this user (caused by "messages.RequestWebView")
 | INFO     | 83 | xempire | Trying to login...

Привет, только настроил и при запуске такое. В чем может быть дело?

**Comment by Alexell** [comment]
Зайди в аккаунт Telegram, у тебя там бот `@empirebot` заблокирован, разблокируй.

**Comment by Ba4ana** [comment]
> Зайди в аккаунт Telegram, у тебя там скорее всего бот `@empirebot` заблокирован, разблокируй.

Да, спасибо ты был прав!
