### ISSUE TITLE
funds and quests won't claimed

### ISSUE THREAD

**Issue by yazdanghalavand** [Alexell/XEmpireBot#87]
Get helper error: 403 Forbidden (contact Alexell to solve this issue)

**Comment by Alexell** [comment]
Quests are not related to the `get_helper()` function and work independently. Send ip to unblock helper.

**Comment by yazdanghalavand** [comment]
212.252.139.36

**Comment by Alexell** [comment]
This IP address is not on the block list. I probably unblocked it en masse when I was processing #84 and #86
