### ISSUE TITLE
Как установить максимальный уровень прокачки скилов?

### ISSUE THREAD

**Issue by mlcni** [Alexell/XEmpireBot#90]
Бот гонит ненужные скилы:

![2024-08-27_16-41-50](https://github.com/user-attachments/assets/7ef07ea9-82dc-4f25-8a29-2f685a960caf)

как  ограничить уровень прокачивания скилов?

**Comment by SmILeTheMobster** [comment]
у тебя есть два варианта либо вкачать их до последнего уровня, либо записать в IGNORED_SKILLS= в env файле

**Comment by Alexell** [comment]
И да, у всех скиллов есть максимальный уровень. Когда навык прокачан до максимума, в игре в списке у этого навыка отображается огонёк и прокачка больше недоступна.
