### ISSUE TITLE
проблемы с прокси

### ISSUE THREAD

**Issue by rixfou** [Alexell/XEmpireBot#94]
привет, софт почему то не видит прокси
![Screenshot_1](https://github.com/user-attachments/assets/646d262c-5a86-479f-8a8d-bb9736e05f3d) (они записаны вот так)
 env выглядит так 
![Screenshot_2](https://github.com/user-attachments/assets/55b3506b-14ab-4051-9146-2183c563f1cd)
![Screenshot_3](https://github.com/user-attachments/assets/24babe9b-95e5-48db-8510-91cca9bee5bb)

**Comment by rixfou** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/dbe75044-90aa-4ca3-900e-aa822a9d9c12)
я заметил ошибку с http, но он все равно не видит

**Comment by rixfou** [comment]
я смог пофиксить это, но почему на аккаунт бот подключается без прокси, хотя видит их
![image](https://github.com/user-attachments/assets/01da3f7f-abec-47c1-8b91-865df3f00aa5)
![image](https://github.com/user-attachments/assets/50650e0f-8191-4344-b0be-44c9e85dba08)

**Comment by Alexell** [comment]
Оффтоп:  должно быть `REF_CODE=hero7532244701`, а не так, как на вашем первом скрине.
А насчет прокси, думаю, что дело в регистрации сессий. Во время регистрации, бот подключается без прокси. А потом уже, когда запускаете бот, он ко всем сессиям подключается через прокси. В любом случае рекомендую обновить бот, т.к. я добавил генерацию ua и более адекватную привязку прокси к сессии.
