### ISSUE TITLE
Файлик с фондами

### ISSUE THREAD

**Issue by PePaRiTB** [Alexell/XEmpireBot#95]
Добрый день! Может сделать локальный файл с фондами, чтобы каждый сам заполнял, а то сейчас не инвестирует?

**Comment by Alexell** [comment]
Бот вполне себе инвестирует, я проверил по логам: 25, 26, 27 и 29 числа было инвестирование. Я пропустил только 28 и 30 число, вылетело из головы. Поставил ежедневное напоминание, чтобы не забывать.
