### ISSUE TITLE
daytime main delay

### ISSUE THREAD

**Issue by PrometheusAla** [Alexell/XEmpireBot#98]
Как отключить данную задержку в исполнении скрипта?

**Comment by Alexell** [comment]
Никак. Она используется только тогда, когда у вас либо выключены тапы, либо вы достигли дневного лимита тапов. В противном случае днем всегда маленькая задержка до восстановления энергии, потом снова тапы.

**Comment by PrometheusAla** [comment]
У меня только баттлы, без тапов. И пауза в час совсем не нужна. 

Спасибо за ответ.

**Comment by Alexell** [comment]
Довольно необычный подход к игре. Зачем PvP без остановки, да еще и без тапов? PvP по сути самая бесполезная функция, там нет гарантии победы и в целом она не приносит особой прибыли. Достаточно раз в час участвовать в битвах, чтобы задание выполнить (по крайней мере раньше какое-то было ежедневное). На тапах больше заработаешь (тапы же прокачиваются теперь).

**Comment by PrometheusAla** [comment]
Тапы идут параллельно. Но в случае основного пасрера где тапы и сражения одновременно. Почему то сражения заканчиваются одним циклом и затем только тапы с паузой на восстановление. Сражения могут принести хорошую прибыль, значительно больше тапов. И стабильно. Сейчас на алмазе )

**Comment by Alexell** [comment]
PvP всегда были раз в час вместе со всеми основными действиями, еще до обновления с постоянными тапами. Я не вижу никаких заработков от PvP. Вы возьмите свой `app.log` за 3-4 суток и сложите результаты всех сессий PvP (поиск по "PvP negotiations finished"). У меня за 3 суток вышло примерно -1.4B (23 лвл, лига алмаз). Таким образом ничего они не приносят, скорее наоборот, но эта цифра небольшая.

**Comment by PrometheusAla** [comment]
На вашем уровне заработка алмаз уже не серьезно. Я еще не дорос. И мне ПВП помогают сильно на текущий момент.

**Comment by Alexell** [comment]
Сделаю щас вам 2 параметра для управления главными задержками дня и ночи.
```
DAY_MAIN_DELAY=3600
NIGHT_MAIN_DELAY=10800
```
Я не знаю, будет ли это нормально работать. В теории, если вы поставите маленькую задержку, постоянной переавторизации не будет (и хорошо, ведь игра такое не любит), но тогда ее вообще не будет и рано или поздно она может слететь. Или нет. Тестить это я не буду. Под вашу ответственность.
