### ISSUE TITLE
how do I farm multiple account?

### ISSUE THREAD

**Issue by MrTimonM** [Alexell/XEmpireBot#99]
If I create a folder named "sessions" and if I input sessions there then will I be able to run multiple account at once?

here is the file format:
sessions -> 1. A1.sessions
               -> 2. A2.sessions

**Comment by mirage2812** [comment]
Аккаунты в таком случае работают параллельно или последовательно в цикле?

**Comment by Alexell** [comment]
Работа с сессиями будет выполняться параллельно (с точки зрения асинхронного кода).
